import Main from '../components/layout/Main';

const AboutUs = () => {
  return (
    <Main>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
      <div>O NAMA</div>
    </Main>
  );
};

export default AboutUs;
