import Main from '../components/layout/Main';

export const metadata = {
  title: 'Kontaktirajte nas | Infotrg',
  description: 'Generated by create next app',
};

const Contact = () => {
  return (
    <Main>
      <div></div>
    </Main>
  );
};

export default Contact;
