export const metadata = {
  title: 'Infotrg | Kontaktirajte nas',
  description: 'Generated by create next app',
};

const Contact = () => {
  return (
    <>
      <div></div>
    </>
  );
};

export default Contact;
